### ISSUE TITLE
Quick replies

### ISSUE THREAD

**Issue by mikedizon** [digitalbreed/jquery.fbmessenger#1]
Awesome plugin! Trying to get this working on my site. Bootstrap seems to have a negative impact on the display of quick replies. Any suggestions on how to resolve?

**Comment by mikedizon** [comment]
Ah, bootstrap uses the class name ".show" and it's set to display: block !important

**Comment by digitalbreed** [comment]
I prefixed all the classes to avoid potential name clashes but there may be something I didn't consider. Best would be if you send me the URL or reproduce the issue with a little jsFiddle?

**Comment by digitalbreed** [comment]
Ah, `.show`... alright, will update that.
