### ISSUE TITLE
Page Block

### ISSUE THREAD

**Issue by Jonnhy** [digitalbreed/jquery.fbmessenger#13]
Hello, I'm using your simulator, but I want it to be possible to click inside the page because I want to put a button for the client. Clicking the button is disabled because I can not even think it could be a "pointer-events: none;" in css but could not find could you give me a help?

**Comment by digitalbreed** [comment]
Jonnhy, I am not sure what you were asking. You can put a button anywhere you want; either near the preview or on top of it, using absolute positioning. The plugin will only affect the containing div.
