### ISSUE TITLE
Export as Video

### ISSUE THREAD

**Issue by ghost** [digitalbreed/jquery.fbmessenger#14]
Can you tell me how can I export the demo as video?

**Comment by digitalbreed** [comment]
Exporting as video is out of scope of this plugin, but you can use my other tool, BotPreview.com! Technically it spawns a headless Chrome on the server, takes screenshots of the page in a fixed interval and combines them using ffmpeg.

**Comment by ghost** [comment]
ok thanks for the BotPreview. Now i got the idea thay i need to capture screenshot and send it to ffmpeg to create video but can you please tell as if when to capture the screenshots and send it to the ffmpeg

**Comment by digitalbreed** [comment]
See e.g. https://github.com/GoogleChrome/puppeteer#usage for a start.

**Comment by ghost** [comment]
thanks
