### ISSUE TITLE
Square aspect ratio for pictures in template

### ISSUE THREAD

**Issue by oscarwroche** [digitalbreed/jquery.fbmessenger#6]
Hi,

Is it possible to display square-shaped pictures in generic templates ? This is done by setting the "image_aspect_ratio" to "square" parameter in the Messenger Send API https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template. Currently my picture gets squeezed to 1.91:1.

Thanks !

**Comment by digitalbreed** [comment]
If this is still interesting for you, I have just pushed a change that allows passing an additional option to use square images, like so:

```
$preview.fbMessenger('showGenericTemplate', [
	// ... items go here
], {
	imageSquare: false
})
```
