### ISSUE TITLE
Can you make a version with a chat functionality? 

### ISSUE THREAD

**Issue by vb0iko** [digitalbreed/jquery.fbmessenger#8]
for example **https://codepen.io/vboyko/pen/RgPWBx**  with JSON requests

**Comment by digitalbreed** [comment]
Apologies for the late response. Of course this is possible with a little additional effort, like adding a real text input field to accept user input. The conversation elements can be added on demand using the `message` interactions after user input submit and server response. However, this additional functionality is out of scope for the plugin and won't be supported natively.
